# Faz o botão "Sponsor" aparecer no topo do repositório.
# Docs: https://docs.github.com/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/displaying-a-sponsor-button-in-your-repository

github: [eumakerdev]
